services:
  web:
    build: "bga-backend-web"
    ports:
      - "80:80"
    depends_on:
      db:
        condition: service_healthy
  db:
    image: "postgres:17"
    restart: always
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      PGUSER: postgres
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - db-data:/var/lib/postgresql/data
    secrets:
      - postgres_password
      - bga_user_password
      - bga_pipeline_password

volumes:
  db-data:
    name: "postgres-data"
    driver: local

secrets:
  postgres_password:
    file: docker/secrets/postgres_password.txt
  bga_user_password:
    file: docker/secrets/bga_user_password.txt
  bga_pipeline_password:
    file: docker/secrets/bga_pipeline_password.txt