name: Push Actions

on: [push]

permissions:
  contents: read

jobs:
  lint-code:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry config virtualenvs.create false
          poetry install --no-interaction --no-ansi
      - name: Linters
        run: |
          black . --check
          isort . --profile=black --check
          flake8
      - name: Type Checkers
        run: mypy .
  tests:

    runs-on: ubuntu-latest
    environment: testing
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry config virtualenvs.create false
          poetry install --no-interaction --no-ansi
      - name: Debug test environment
        run: |
          echo "PWD=$(pwd)"
          echo "GITHUB_WORKSPACE=$GITHUB_WORKSPACE"
          echo "PYTHONPATH=$GITHUB_WORKSPACE/src"
          ls -la $GITHUB_WORKSPACE/src
          python -c "import sys; print(sys.path)"
      - name: Test with pytest
        run: |
          PYTHONPATH=$GITHUB_WORKSPACE/src pytest
